import React,{useCallback,useEffect,useState}from'react';import{Download,RefreshCw,Search,ShieldCheck}from'lucide-react';import{authHeaders}from'../lib/auth';
const API=(import.meta.env.VITE_PHANTOM_API_URL??'http://localhost:8000').replace(/\/$/,'');
export default function AuditLogs(){const[events,setEvents]=useState<any[]>([]),[q,setQ]=useState(''),[actor,setActor]=useState(''),[resource,setResource]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[loading,setLoading]=useState(false);
const params=()=>{const p=new URLSearchParams({limit:'500'});if(q)p.set('q',q);if(actor)p.set('actor',actor);if(resource)p.set('resource_type',resource);if(from)p.set('date_from',new Date(from).toISOString());if(to)p.set('date_to',new Date(to+'T23:59:59').toISOString());return p};
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`${API}/api/v1/audit?${params()}`,{headers:authHeaders()});setEvents(r.ok?await r.json():[])}finally{setLoading(false)}},[q,actor,resource,from,to]);useEffect(()=>{void load()},[load]);
async function exp(){const r=await fetch(`${API}/api/v1/audit/export.csv?${params()}`,{headers:authHeaders()});if(!r.ok)return;const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='phantom-audit.csv';a.click();URL.revokeObjectURL(u)}
return <div className="min-h-full bg-phantom-bg p-6 lg:p-8"><div className="max-w-7xl mx-auto"><header className="flex justify-between items-end mb-6"><div><div className="text-xs font-mono uppercase text-phantom-cyan">Governance</div><h1 className="text-2xl font-semibold mt-2">Audit Logs</h1><p className="text-sm text-phantom-text-secondary mt-1">Searchable, workspace-scoped record of security-relevant actions.</p></div><div className="flex gap-2"><button onClick={()=>void exp()} className="h-9 px-3 border border-phantom-border rounded flex items-center gap-2 text-xs"><Download size={13}/>Export CSV</button><button onClick={()=>void load()} className="h-9 px-3 border border-phantom-border rounded"><RefreshCw size={13}/></button></div></header>
<div className="grid md:grid-cols-5 gap-2 mb-5"><label className="relative md:col-span-2"><Search size={14} className="absolute left-3 top-3 text-phantom-text-tertiary"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search action/resource…" className="w-full h-10 pl-9 bg-phantom-surface border border-phantom-border rounded"/></label><input value={actor} onChange={e=>setActor(e.target.value)} placeholder="Actor" className="h-10 px-3 bg-phantom-surface border border-phantom-border rounded"/><input value={resource} onChange={e=>setResource(e.target.value)} placeholder="Resource type" className="h-10 px-3 bg-phantom-surface border border-phantom-border rounded"/><div className="flex gap-1"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="min-w-0 h-10 px-2 bg-phantom-surface border border-phantom-border rounded"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="min-w-0 h-10 px-2 bg-phantom-surface border border-phantom-border rounded"/></div></div>
<div className="border border-phantom-border rounded-xl overflow-hidden bg-phantom-surface">{loading?<div className="p-10 text-center">Loading…</div>:events.length===0?<div className="p-10 text-center text-sm text-phantom-text-tertiary"><ShieldCheck className="mx-auto mb-2"/>No matching audit events.</div>:events.map(e=><div key={e.id} className="grid lg:grid-cols-[170px_1fr_180px_1fr] gap-3 p-4 border-b border-phantom-border"><div className="text-[11px] font-mono text-phantom-text-tertiary">{e.created_at?new Date(e.created_at).toLocaleString():'—'}</div><div><div className="text-sm font-medium">{e.action}</div><div className="text-[11px] text-phantom-text-tertiary">{e.resource_type} · {e.resource_id??'—'}</div></div><div className="text-xs truncate">{e.actor}</div><pre className="text-[10px] whitespace-pre-wrap break-all text-phantom-text-tertiary">{JSON.stringify(e.metadata??{})}</pre></div>)}</div></div></div>}
