import React, { useEffect, useState } from 'react';
import { Activity, Search, ShieldCheck, RefreshCw } from 'lucide-react';

const API = (import.meta.env.VITE_PHANTOM_API_URL ?? 'http://localhost:8000').replace(/\/$/, '');
export default function AuditLogs() {
  const [events, setEvents] = useState<any[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); fetch(`${API}/api/v1/audit`, { headers: { 'X-PHANTOM-Role': 'admin' } }).then(r => r.ok ? r.json() : []).then(setEvents).catch(() => setEvents([])).finally(() => setLoading(false)); };
  useEffect(load, []);
  const filtered = events.filter(e => `${e.actor} ${e.action} ${e.resource_type} ${e.resource_id ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="min-h-full bg-phantom-bg p-6 lg:p-8"><div className="max-w-7xl mx-auto"><div className="flex items-end justify-between mb-7"><div><div className="text-xs font-mono uppercase tracking-widest text-phantom-cyan mb-2">Governance</div><h1 className="text-2xl font-semibold">Audit Logs</h1><p className="text-sm text-phantom-text-secondary mt-2">Trace security-relevant changes made through the PHANTOM API.</p></div><button onClick={load} className="h-9 px-3 border border-phantom-border rounded-lg text-xs flex items-center gap-2 hover:bg-phantom-surface"><RefreshCw size={14}/> Refresh</button></div><div className="relative mb-5"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-phantom-text-tertiary"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter actor, action, resource..." className="w-full h-10 pl-9 pr-3 rounded-lg border border-phantom-border bg-phantom-surface text-sm outline-none focus:border-phantom-cyan"/></div><div className="border border-phantom-border rounded-xl overflow-hidden bg-phantom-surface">{loading ? <div className="p-10 text-center text-sm text-phantom-text-tertiary">Loading audit events…</div> : filtered.length === 0 ? <div className="p-10 text-center"><ShieldCheck size={20} className="mx-auto mb-3 text-phantom-text-tertiary"/><div className="text-sm text-phantom-text-secondary">No audit events match this filter.</div></div> : filtered.map(e => <div key={e.id} className="grid grid-cols-[170px_1fr_130px_150px] gap-4 items-center px-4 py-3 border-b last:border-b-0 border-phantom-border"><div className="text-[11px] font-mono text-phantom-text-tertiary">{e.created_at ? new Date(e.created_at).toLocaleString() : '—'}</div><div><div className="text-sm font-medium flex items-center gap-2"><Activity size={13} className="text-phantom-cyan"/>{e.action}</div><div className="text-[11px] text-phantom-text-tertiary mt-1">{e.resource_type}{e.resource_id ? ` · ${e.resource_id.slice(0, 12)}` : ''}</div></div><div className="text-xs text-phantom-text-secondary truncate">{e.actor}</div><pre className="text-[10px] font-mono text-phantom-text-tertiary truncate">{JSON.stringify(e.metadata ?? {})}</pre></div>)}</div></div></div>;
}
