import React,{useEffect,useState}from'react';
import{KeyRound,Plus,RefreshCw,Trash2,RotateCcw}from'lucide-react';
import{authHeaders,getSession}from'../lib/auth';

const API=(import.meta.env.VITE_PHANTOM_API_URL??'http://localhost:8000').replace(/\/$/,'');
type Credential={id:string;name:string;kind:'basic'|'bearer'|'api_key';username?:string|null;header_name?:string|null;created_at?:string|null;last_used_at?:string|null};

export default function Credentials(){
 const session=getSession();
 const[items,setItems]=useState<Credential[]>([]),[name,setName]=useState(''),[kind,setKind]=useState<Credential['kind']>('bearer'),[secret,setSecret]=useState(''),[username,setUsername]=useState(''),[headerName,setHeaderName]=useState('X-API-Key'),[rotateId,setRotateId]=useState(''),[rotateSecret,setRotateSecret]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const canManage=['owner','admin','security_lead'].includes((session?.role??'').toLowerCase());
 const load=async()=>{setLoading(true);try{const r=await fetch(API+'/api/v1/workspaces/current/credentials',{headers:authHeaders()});if(!r.ok)throw new Error(await r.text());setItems(await r.json())}catch(e){setError(e instanceof Error?e.message:'Unable to load credentials')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 async function create(){setError('');try{const body={name,kind,secret,username:kind==='basic'?username||null:null,header_name:kind==='api_key'?headerName||null:null};const r=await fetch(API+'/api/v1/workspaces/current/credentials',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());setName('');setSecret('');setUsername('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create credential')}};
 async function rotate(){if(!rotateId||!rotateSecret)return;setError('');try{const r=await fetch(API+'/api/v1/workspaces/current/credentials/'+encodeURIComponent(rotateId)+'/rotate',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({secret:rotateSecret})});if(!r.ok)throw new Error(await r.text());setRotateId('');setRotateSecret('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to rotate credential')}};
 async function remove(id:string){if(!confirm('Delete this assessment credential? Existing scans keep their historical credential ID but cannot use it after deletion.'))return;const r=await fetch(API+'/api/v1/workspaces/current/credentials/'+encodeURIComponent(id),{method:'DELETE',headers:authHeaders()});if(!r.ok){setError(await r.text());return}await load()};
 return <div className="min-h-full bg-phantom-bg p-6 lg:p-8"><div className="max-w-6xl mx-auto"><div className="flex items-end justify-between mb-7"><div><div className="text-xs font-mono uppercase tracking-widest text-phantom-cyan mb-2">Assessment secrets</div><h1 className="text-2xl font-semibold tracking-tight">Credentials</h1><p className="text-sm text-phantom-text-secondary mt-2">Manage encrypted credentials used only for authorized authenticated assessments.</p></div><button onClick={()=>void load()} className="h-9 px-3 rounded-lg border border-phantom-border text-xs flex items-center gap-2"><RefreshCw size={13}/>Refresh</button></div>
 <div className="grid lg:grid-cols-[360px_1fr] gap-5">
  {canManage?<section className="border border-phantom-border bg-phantom-surface rounded-xl p-5 h-fit"><div className="flex items-center gap-2 text-sm font-semibold mb-4"><Plus size={16} className="text-phantom-cyan"/>Add credential</div><div className="space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Credential name" className="w-full h-10 rounded-lg border border-phantom-border bg-phantom-bg px-3 text-xs outline-none"/><select value={kind} onChange={e=>setKind(e.target.value as Credential['kind'])} className="w-full h-10 rounded-lg border border-phantom-border bg-phantom-bg px-3 text-xs"><option value="bearer">Bearer token</option><option value="basic">Basic auth</option><option value="api_key">API key</option></select>{kind==='basic'&&<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" className="w-full h-10 rounded-lg border border-phantom-border bg-phantom-bg px-3 text-xs outline-none"/>}{kind==='api_key'&&<input value={headerName} onChange={e=>setHeaderName(e.target.value)} placeholder="Header (X-API-Key or Authorization)" className="w-full h-10 rounded-lg border border-phantom-border bg-phantom-bg px-3 text-xs outline-none"/>}<input value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Secret" type="password" className="w-full h-10 rounded-lg border border-phantom-border bg-phantom-bg px-3 text-xs outline-none"/><button onClick={()=>void create()} disabled={!name||!secret||(kind==='basic'&&!username)} className="w-full h-10 rounded-lg bg-phantom-text-primary text-black text-xs font-semibold disabled:opacity-40">Store encrypted credential</button></div><p className="text-[11px] text-phantom-text-tertiary mt-3">The secret is never returned after creation. Production deployments must configure PHANTOM_CREDENTIAL_ENCRYPTION_KEY.</p></section>:<section className="border border-phantom-border bg-phantom-surface rounded-xl p-5 h-fit"><KeyRound size={18} className="text-phantom-cyan mb-3"/><div className="text-sm font-semibold">Credential management restricted</div><p className="text-xs text-phantom-text-secondary mt-2">Only workspace owners, admins and security leads can create, rotate or delete assessment credentials. Existing credentials can still be selected when launching a scan.</p></section>}
  <section className="border border-phantom-border bg-phantom-surface rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-phantom-border text-xs font-semibold uppercase tracking-wider text-phantom-text-tertiary">Credentials · {items.length}</div>{loading?<div className="p-10 text-center text-sm text-phantom-text-tertiary">Loading…</div>:items.length===0?<div className="p-10 text-center text-sm text-phantom-text-tertiary">No assessment credentials configured.</div>:items.map(c=><div key={c.id} className="px-4 py-3 border-b last:border-0 border-phantom-border"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg border border-phantom-border bg-phantom-bg flex items-center justify-center"><KeyRound size={15} className="text-phantom-cyan"/></div><div className="min-w-0 flex-1"><div className="text-sm font-medium truncate">{c.name}</div><div className="text-[11px] text-phantom-text-tertiary font-mono">{c.kind}{c.username?' · '+c.username:''}</div></div>{canManage&&<><button onClick={()=>{setRotateId(c.id);setRotateSecret('')}} className="p-2 rounded hover:bg-phantom-panel text-phantom-text-tertiary" title="Rotate"><RotateCcw size={14}/></button><button onClick={()=>void remove(c.id)} className="p-2 rounded hover:bg-phantom-panel text-phantom-coral" title="Delete"><Trash2 size={14}/></button></>}</div>{rotateId===c.id&&canManage&&<div className="mt-3 flex gap-2"><input value={rotateSecret} onChange={e=>setRotateSecret(e.target.value)} type="password" placeholder="New secret" className="flex-1 h-9 rounded-lg border border-phantom-border bg-phantom-bg px-3 text-xs"/><button onClick={()=>void rotate()} disabled={!rotateSecret} className="h-9 px-3 rounded-lg border border-phantom-border text-xs disabled:opacity-40">Rotate</button></div>}</div>)}</section>
 </div>{error&&<div className="mt-4 text-xs text-phantom-coral whitespace-pre-wrap">{error}</div>}</div></div>
}
