import React,{useEffect,useState}from'react';
import{createCredential,deleteCredential,listCredentials,type AssessmentCredential}from'../lib/phantomApi';
import{useRBAC}from'../lib/RBACProvider';
export default function Credentials(){
 const{can}=useRBAC();const[rows,setRows]=useState<AssessmentCredential[]>([]);const[name,setName]=useState('');const[kind,setKind]=useState<'basic'|'bearer'|'api_key'>('bearer');const[username,setUsername]=useState('');const[secret,setSecret]=useState('');const[error,setError]=useState('');
 const load=()=>void listCredentials().then(setRows).catch(e=>setError(e instanceof Error?e.message:'Unable to load credentials'));useEffect(load,[]);
 async function create(){setError('');try{await createCredential({name,kind,username:kind==='basic'?username:undefined,header_name:kind==='api_key'?'Authorization':undefined,secret});setName('');setUsername('');setSecret('');load()}catch(e){setError(e instanceof Error?e.message:'Unable to create credential')}}
 async function remove(id:string){try{await deleteCredential(id);load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete credential')}}
 return <div className="min-h-full bg-phantom-bg p-6 lg:p-8"><div className="max-w-5xl mx-auto"><h1 className="text-2xl font-semibold">Assessment Credentials</h1><p className="text-sm text-phantom-text-secondary mt-1 mb-6">Encrypted server-side credentials for authorized authenticated assessments. Secrets are never returned by the API.</p>{can('scan:credentials')&&<section className="border border-phantom-border bg-phantom-surface rounded-xl p-5 mb-6"><div className="grid md:grid-cols-2 gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Credential name" className="h-10 px-3 rounded-lg border border-phantom-border bg-phantom-bg"/><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)} className="h-10 px-3 rounded-lg border border-phantom-border bg-phantom-bg"><option value="bearer">Bearer token</option><option value="basic">Basic auth</option><option value="api_key">API key</option></select>{kind==='basic'&&<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" className="h-10 px-3 rounded-lg border border-phantom-border bg-phantom-bg"/>}<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Secret" className="h-10 px-3 rounded-lg border border-phantom-border bg-phantom-bg"/><button onClick={()=>void create()} disabled={!name||!secret} className="h-10 rounded-lg bg-phantom-text-primary text-black font-semibold disabled:opacity-50">Store credential</button></div></section>}{error&&<div className="mb-4 text-xs text-phantom-coral">{error}</div>}<section className="border border-phantom-border rounded-xl overflow-hidden bg-phantom-surface">{rows.map(r=><div key={r.id} className="flex items-center gap-4 px-4 py-3 border-b border-phantom-border"><div className="flex-1"><div className="text-sm font-medium">{r.name}</div><div className="text-xs text-phantom-text-tertiary">{r.kind}{r.username?' · '+r.username:''}</div></div>{can('scan:credentials')&&<button onClick={()=>void remove(r.id)} className="text-xs text-phantom-coral">Delete</button>}</div>)}{rows.length===0&&<div className="p-8 text-center text-sm text-phantom-text-tertiary">No assessment credentials stored.</div>}</section></div></div>
}