import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,CheckCircle2,Download,Globe,Link2,RefreshCw,Server,Wifi}from'lucide-react';
import{authHeaders}from'../lib/auth';
const API=(import.meta.env.VITE_PHANTOM_API_URL??'http://localhost:8000').replace(/\/$/,'');
type Connection={key:string;status:string;pid:number|null;process:string|null;local:string|null;remote:string|null;risk:string;risk_score:number;risk_reasons:string[]};
type Snapshot={hostname:string;connection_count:number;new_connection_count:number;connections:Connection[];network_io:{send_bytes_per_second:number;recv_bytes_per_second:number};vpn_interfaces:string[]};
type Anomaly={status:string;severity:string;reasons:string[];baseline:Record<string,number>};
type Event={id:string;kind:string;severity:string;summary:string;explanation:string;finding_id:string|null;acknowledged_at:string|null;created_at:string;data:Record<string,unknown>;baseline:Record<string,unknown>};
type Baseline={metric:string;value:{mean?:number;last?:number};sample_count:number};
export default function NetWatch(){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[anomaly,setAnomaly]=useState<Anomaly|null>(null),[events,setEvents]=useState<Event[]>([]),[baselines,setBaselines]=useState<Baseline[]>([]),[kind,setKind]=useState(''),[error,setError]=useState(''),[paused,setPaused]=useState(false);
 const load=useCallback(async()=>{try{setError('');const q=kind?'?kind='+encodeURIComponent(kind):'';const[s,a,h,b]=await Promise.all([fetch(API+'/api/v1/network/snapshot',{headers:authHeaders()}),fetch(API+'/api/v1/network/anomaly',{headers:authHeaders()}),fetch(API+'/api/v1/net-watch/timeline'+q,{headers:authHeaders()}),fetch(API+'/api/v1/net-watch/baselines',{headers:authHeaders()})]);if(!s.ok||!a.ok||!h.ok)throw new Error('Net-Watch telemetry unavailable');setSnapshot(await s.json());const ar=await a.json();setAnomaly(ar.anomaly);setEvents(await h.json());if(b.ok)setBaselines(await b.json())}catch(e){setError(e instanceof Error?e.message:'Net-Watch unavailable')}},[kind]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(paused)return;const t=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(t)},[paused,load]);
 const risky=useMemo(()=>[...(snapshot?.connections??[])].sort((a,b)=>b.risk_score-a.risk_score).slice(0,10),[snapshot]);
 const ack=async(e:Event)=>{const r=await fetch(API+'/api/v1/net-watch/events/'+e.id+'/acknowledge',{method:'PATCH',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({acknowledged:!e.acknowledged_at})});if(r.ok)void load()};
 const exportFile=async(format:'csv'|'json')=>{const r=await fetch(API+'/api/v1/net-watch/export.'+format,{headers:authHeaders()});if(!r.ok)return setError(await r.text());const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='net-watch.'+format;a.click();URL.revokeObjectURL(url)};
 const rate=(snapshot?.network_io.send_bytes_per_second??0)+(snapshot?.network_io.recv_bytes_per_second??0);
 return <div className="min-h-full bg-phantom-bg p-6 lg:p-8"><div className="max-w-[1500px] mx-auto"><header className="flex items-end justify-between mb-6"><div><div className="text-xs font-mono uppercase tracking-[.18em] text-phantom-cyan mb-2">Net-Watch</div><h1 className="text-2xl font-semibold">Network Operations & History</h1><p className="text-sm text-phantom-text-secondary mt-2">Native OS telemetry with persistent timelines, baselines, anomaly explanations and PHANTOM correlation.</p></div><div className="flex gap-2"><button onClick={()=>void exportFile('csv')} className="h-9 px-3 rounded-lg border border-phantom-border text-xs flex items-center gap-2"><Download size={13}/>CSV</button><button onClick={()=>void exportFile('json')} className="h-9 px-3 rounded-lg border border-phantom-border text-xs">JSON</button><button onClick={()=>setPaused(x=>!x)} className="h-9 px-3 rounded-lg border border-phantom-border text-xs">{paused?'Resume':'Pause'}</button><button onClick={()=>void load()} className="h-9 px-3 rounded-lg border border-phantom-border text-xs"><RefreshCw size={13}/></button></div></header>
 {error&&<div className="mb-5 rounded-lg border border-phantom-coral/30 bg-phantom-coral/10 px-4 py-3 text-xs text-phantom-coral">{error}</div>}
 <div className="grid md:grid-cols-4 gap-3 mb-5"><Metric icon={<Activity size={15}/>} label="Connections" value={snapshot?.connection_count??0}/><Metric icon={<Globe size={15}/>} label="New / sample" value={snapshot?.new_connection_count??0}/><Metric icon={<Server size={15}/>} label="Traffic / sec" value={formatRate(rate)}/><Metric icon={<Wifi size={15}/>} label="VPN interfaces" value={snapshot?.vpn_interfaces?.length??0}/></div>
 <div className="grid lg:grid-cols-[1fr_360px] gap-5 mb-6"><section className="border border-phantom-border bg-phantom-surface rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-phantom-border text-xs font-semibold uppercase tracking-wider text-phantom-text-tertiary">Live connections</div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-[10px] uppercase text-phantom-text-tertiary border-b border-phantom-border"><th className="p-3">Process</th><th>Local</th><th>Remote</th><th>State</th><th>Risk</th></tr></thead><tbody>{risky.map(c=><tr key={c.key} className="border-b border-phantom-border/70"><td className="p-3">{c.process??'Unknown'} <span className="text-phantom-text-tertiary">PID {c.pid??'—'}</span></td><td className="font-mono text-[10px]">{c.local??'—'}</td><td className="font-mono text-[10px]">{c.remote??'—'}</td><td>{c.status}</td><td className={c.risk==='high'?'text-phantom-coral':c.risk==='medium'?'text-phantom-amber':''}>{c.risk}</td></tr>)}{!risky.length&&<tr><td colSpan={5} className="p-8 text-center text-phantom-text-tertiary">No live connections.</td></tr>}</tbody></table></div></section>
 <aside className="space-y-4"><section className="border border-phantom-border bg-phantom-surface rounded-xl p-5"><div className="flex items-center gap-2 text-xs font-semibold uppercase text-phantom-text-tertiary"><AlertTriangle size={14}/>Anomaly explanation</div><div className="mt-3 text-sm">{anomaly?.status??'learning'} · {anomaly?.severity??'info'}</div><div className="mt-3 space-y-2">{(anomaly?.reasons??[]).map((x,i)=><div key={i} className="text-xs text-phantom-text-secondary border-l border-phantom-border pl-3">{x}</div>)}{!anomaly?.reasons?.length&&<div className="text-xs text-phantom-text-tertiary">Baseline is learning; no significant deviation detected.</div>}</div></section><section className="border border-phantom-border bg-phantom-surface rounded-xl p-5"><div className="text-xs font-semibold uppercase text-phantom-text-tertiary mb-3">Persisted baselines</div>{baselines.map(b=><div key={b.metric} className="flex justify-between text-xs py-1"><span>{b.metric.replaceAll('_',' ')}</span><span className="font-mono">{Number(b.value.mean??0).toFixed(1)} · n={b.sample_count}</span></div>)}</section></aside></div>
 <section className="border border-phantom-border bg-phantom-surface rounded-xl overflow-hidden"><div className="p-4 border-b border-phantom-border flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-phantom-text-tertiary">Historical telemetry</div><div className="text-[10px] text-phantom-text-tertiary mt-1">Connections · process lifecycle · interface snapshots · anomalies</div></div><div className="flex gap-1">{['','connection','process','interface','anomaly'].map(x=><button key={x||'all'} onClick={()=>setKind(x)} className={'px-2.5 py-1 rounded border text-[10px] '+(kind===x?'border-phantom-cyan text-phantom-cyan':'border-phantom-border text-phantom-text-tertiary')}>{x||'all'}</button>)}</div></div><div className="divide-y divide-phantom-border">{events.map(e=><div key={e.id} className="p-4 flex justify-between gap-4"><div><div className="flex items-center gap-2"><span className={'text-[10px] uppercase '+(e.severity==='high'||e.severity==='critical'?'text-phantom-coral':'text-phantom-cyan')}>{e.severity}</span><span className="text-sm font-medium">{e.summary}</span></div><div className="text-xs text-phantom-text-secondary mt-1">{e.explanation}</div><div className="text-[10px] font-mono text-phantom-text-tertiary mt-2">{new Date(e.created_at).toLocaleString()} · {e.kind}</div>{e.finding_id&&<a className="inline-flex gap-1 items-center text-xs text-phantom-cyan mt-2" href={'/investigation?finding='+e.finding_id}><Link2 size={11}/>Correlated PHANTOM finding</a>}</div><button onClick={()=>void ack(e)} className="h-8 px-2 rounded border border-phantom-border text-[10px] flex items-center gap-1">{e.acknowledged_at&&<CheckCircle2 size={12}/>} {e.acknowledged_at?'Acknowledged':'Acknowledge'}</button></div>)}{!events.length&&<div className="p-10 text-center text-sm text-phantom-text-tertiary">History will populate as the native collector observes changes.</div>}</div></section></div></div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-xl border border-phantom-border bg-phantom-surface p-4"><div className="flex items-center gap-2 text-[10px] uppercase text-phantom-text-tertiary">{icon}{label}</div><div className="mt-2 text-2xl font-semibold font-mono">{value}</div></div>}
function formatRate(n:number){if(n<1024)return Math.round(n)+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(1)+' GB'}
