import React,{useEffect,useState}from'react';
import{Activity,CheckCircle2,Download,Link2,RefreshCw,ShieldAlert}from'lucide-react';
import{authHeaders}from'../lib/auth';
const API=(import.meta.env.VITE_PHANTOM_API_URL??'http://localhost:8000').replace(/\/$/,'');
type Event={id:string;kind:string;severity:string;summary:string;explanation:string;finding_id:string|null;acknowledged_at:string|null;created_at:string;data:Record<string,unknown>;baseline:Record<string,unknown>};
type Baseline={metric:string;value:{mean?:number;last?:number};sample_count:number;updated_at:string|null};
export default function NetWatch(){
 const[events,setEvents]=useState<Event[]>([]),[baselines,setBaselines]=useState<Baseline[]>([]),[status,setStatus]=useState<{enabled:boolean;last_event_at:string|null;sensor:string|null}|null>(null),[error,setError]=useState(''),[kind,setKind]=useState('');
 const load=async()=>{try{setError('');const q=kind?'?kind='+encodeURIComponent(kind):'';const [r,b,s]=await Promise.all([fetch(API+'/api/v1/net-watch/timeline'+q,{headers:authHeaders()}),fetch(API+'/api/v1/net-watch/baselines',{headers:authHeaders()}),fetch(API+'/api/v1/net-watch/status',{headers:authHeaders()})]);if(!r.ok)throw new Error(await r.text());setEvents(await r.json());if(b.ok)setBaselines(await b.json());if(s.ok)setStatus(await s.json())}catch(e){setError(e instanceof Error?e.message:'Unable to load Net-Watch')}};
 useEffect(()=>{void load()},[kind]);
 const ack=async(e:Event)=>{const r=await fetch(API+'/api/v1/net-watch/events/'+e.id+'/acknowledge',{method:'PATCH',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({acknowledged:!e.acknowledged_at})});if(r.ok)void load()};
 const exportCsv=async()=>{const r=await fetch(API+'/api/v1/net-watch/export.csv',{headers:authHeaders()});if(!r.ok)return setError(await r.text());const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='net-watch.csv';a.click();URL.revokeObjectURL(u)};
 return <div className="flex flex-col h-full bg-phantom-bg"><header className="p-6 border-b border-phantom-border bg-phantom-surface/50"><div className="flex items-center justify-between"><div><div className="text-xs font-mono uppercase tracking-widest text-phantom-cyan mb-2">Native telemetry</div><h1 className="text-xl font-semibold">Net-Watch</h1><p className="text-sm text-phantom-text-secondary mt-1">Historical connections, processes, interfaces and correlated network anomalies.</p></div><div className="flex gap-2"><button onClick={exportCsv} className="h-9 px-3 rounded-lg border border-phantom-border text-xs flex items-center gap-2"><Download size={13}/>Export</button><button onClick={()=>void load()} className="h-9 px-3 rounded-lg border border-phantom-border text-xs flex items-center gap-2"><RefreshCw size={13}/>Refresh</button></div></div></header>
 <main className="p-6 overflow-y-auto"><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-5"><div className="rounded-xl border border-phantom-border bg-phantom-surface p-4"><div className="text-[10px] uppercase tracking-wider text-phantom-text-tertiary">Collector</div><div className="text-sm mt-1">{status?.enabled?"Active":"Unavailable"}</div><div className="text-[10px] text-phantom-text-tertiary mt-1">{status?.sensor||"No sensor sample yet"}</div></div>{baselines.slice(0,2).map(b=><div key={b.metric} className="rounded-xl border border-phantom-border bg-phantom-surface p-4"><div className="text-[10px] uppercase tracking-wider text-phantom-text-tertiary">{b.metric.replaceAll("_"," ")}</div><div className="text-lg mt-1">{Math.round(b.value.last??b.value.mean??0)}</div><div className="text-[10px] text-phantom-text-tertiary">{b.sample_count} baseline samples · mean {Number(b.value.mean??0).toFixed(1)}</div></div>)}</div><div className="flex gap-2 mb-5">{['','connection','process','interface','anomaly'].map(x=><button key={x||'all'} onClick={()=>setKind(x)} className={'px-3 py-1.5 rounded-lg border text-xs '+(kind===x?'border-phantom-cyan text-phantom-cyan bg-phantom-cyan/10':'border-phantom-border text-phantom-text-secondary')}>{x||'all'}</button>)}</div>{error&&<div className="mb-4 text-xs text-phantom-coral">{error}</div>}<div className="space-y-3">{events.map(e=><div key={e.id} className="rounded-xl border border-phantom-border bg-phantom-surface p-4"><div className="flex justify-between gap-4"><div className="flex gap-3"><div className={'mt-0.5 '+(e.severity==='high'||e.severity==='critical'?'text-phantom-coral':'text-phantom-cyan')}>{e.kind==='anomaly'?<ShieldAlert size={17}/>:<Activity size={17}/>}</div><div><div className="text-sm font-medium">{e.summary}</div><div className="text-xs text-phantom-text-secondary mt-1">{e.explanation||'Telemetry observation recorded from the host.'}</div><div className="text-[10px] font-mono text-phantom-text-tertiary mt-2">{new Date(e.created_at).toLocaleString()} · {e.kind} · {e.severity}</div>{e.finding_id&&<a href={'/investigation?finding='+e.finding_id} className="inline-flex items-center gap-1 mt-2 text-xs text-phantom-cyan"><Link2 size={11}/>Open correlated PHANTOM finding</a>}</div></div><button onClick={()=>void ack(e)} className="h-8 px-2 rounded-lg border border-phantom-border text-xs flex items-center gap-1.5">{e.acknowledged_at?<CheckCircle2 size={13}/>:null}{e.acknowledged_at?'Acknowledged':'Acknowledge'}</button></div></div>)}{events.length===0&&!error&&<div className="py-16 text-center text-sm text-phantom-text-tertiary">No historical Net-Watch telemetry has been recorded yet.</div>}</div></main></div>
}