import React,{useEffect,useMemo,useState}from'react';
import{Download,FileText,History,Plus,RefreshCw,Save,ShieldAlert}from'lucide-react';
import{authHeaders}from'../lib/auth';import{type Scan,getScan}from'../lib/phantomApi';
const API=(import.meta.env.VITE_PHANTOM_API_URL??'http://localhost:8000').replace(/\/$/,'');
type Report={id:string;scan_id:string;title:string;template:string;status:string;metadata:Record<string,string>;branding:Record<string,string>;sections:{title:string;content:string}[];finding_ids:string[];include_evidence:boolean;current_version:number;updated_at:string};
export default function Reports(){
 const[scans,setScans]=useState<Scan[]>([]),[scanId,setScanId]=useState(''),[scan,setScan]=useState<any>(null),[reports,setReports]=useState<Report[]>([]),[active,setActive]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[versions,setVersions]=useState<any[]>([]),[downloads,setDownloads]=useState<any[]>([]);
 const api=async(path:string,init:RequestInit={})=>{const r=await fetch(API+path,{...init,headers:{...authHeaders(),'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r};
 const load=async()=>{try{const[s,r]=await Promise.all([api('/api/v1/scans'),api('/api/v1/reports')]);const ss=await s.json();setScans(ss);setReports(await r.json());if(!scanId&&ss[0])setScanId(ss[0].id)}catch(e){setError(String(e))}};
 useEffect(()=>{void load()},[]);useEffect(()=>{if(scanId)getScan(scanId).then(setScan).catch(e=>setError(String(e)))},[scanId]);
 useEffect(()=>{if(active)Promise.all([api('/api/v1/reports/'+active.id+'/versions').then(r=>r.json()),api('/api/v1/reports/'+active.id+'/downloads').then(r=>r.json())]).then(([v,d])=>{setVersions(v);setDownloads(d)}).catch(()=>{})},[active?.id,active?.current_version]);
 const findings=scan?.findings??[],selected=new Set(active?.finding_ids??[]);const counts=useMemo(()=>Object.fromEntries(['critical','high','medium','low','info'].map(s=>[s,findings.filter((f:any)=>f.severity===s).length])),[findings]);
 async function create(){if(!scanId)return;setBusy(true);try{const r=await api('/api/v1/reports',{method:'POST',body:JSON.stringify({scan_id:scanId,title:'PHANTOM Security Assessment',template:'technical',finding_ids:findings.map((f:any)=>f.id),include_evidence:true,branding:{company:'PHANTOM'},metadata:{client:'',author:''}})});const x=await r.json();setActive(x);await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function save(patch:Partial<Report>={}){if(!active)return;setBusy(true);try{const body={title:active.title,template:active.template,status:active.status,metadata:active.metadata,branding:active.branding,sections:active.sections,finding_ids:active.finding_ids,include_evidence:active.include_evidence,...patch};const r=await api('/api/v1/reports/'+active.id,{method:'PATCH',body:JSON.stringify(body)});setActive(await r.json());await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function download(fmt:'pdf'|'html'){if(!active)return;const r=await fetch(API+`/api/v1/reports/${active.id}.${fmt}`,{headers:authHeaders()});if(!r.ok){setError(await r.text());return}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`report-${active.id}-v${active.current_version}.${fmt}`;a.click();URL.revokeObjectURL(url);setActive({...active})}
 const toggle=(id:string)=>active&&setActive({...active,finding_ids:selected.has(id)?active.finding_ids.filter(x=>x!==id):[...active.finding_ids,id]});
 return <div className="flex flex-col h-full bg-phantom-bg"><header className="p-6 border-b border-phantom-border bg-phantom-surface/50"><div className="flex justify-between gap-4"><div><div className="text-xs font-mono uppercase tracking-widest text-phantom-cyan mb-2">Evidence delivery</div><h1 className="text-xl font-semibold">Report System</h1><p className="text-sm text-phantom-text-secondary mt-1">Versioned executive and technical assessment reports.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="h-9 px-3 border border-phantom-border rounded-lg text-xs"><RefreshCw size={13}/></button><button onClick={()=>void create()} disabled={!scanId||busy} className="h-9 px-4 bg-phantom-text-primary text-black rounded-lg text-xs flex gap-2 items-center"><Plus size={14}/>New report</button></div></div></header>
 <main className="flex-1 overflow-auto p-6"><div className="max-w-7xl mx-auto space-y-5">{error&&<div className="border border-phantom-coral/30 bg-phantom-coral/10 p-3 rounded text-xs text-phantom-coral">{error}</div>}
 <div className="grid lg:grid-cols-[280px_1fr] gap-5"><aside className="space-y-3"><section className="border border-phantom-border bg-phantom-surface rounded-xl p-4"><label className="text-[10px] uppercase text-phantom-text-tertiary">Source scan</label><select value={scanId} onChange={e=>setScanId(e.target.value)} className="mt-2 w-full h-10 bg-phantom-bg border border-phantom-border rounded px-2 text-xs">{scans.map(s=><option key={s.id} value={s.id}>{s.target}</option>)}</select></section><section className="border border-phantom-border bg-phantom-surface rounded-xl p-3"><div className="text-xs font-semibold mb-2">Report history</div>{reports.map(r=><button key={r.id} onClick={()=>{setActive(r);setScanId(r.scan_id)}} className="w-full text-left p-3 rounded hover:bg-phantom-bg border-b border-phantom-border/50"><div className="text-xs font-medium truncate">{r.title}</div><div className="text-[10px] text-phantom-text-tertiary">{r.template} · {r.status} · v{r.current_version}</div></button>)}</section></aside>
 {!active?<section className="border border-phantom-border bg-phantom-surface rounded-xl p-16 text-center text-sm text-phantom-text-tertiary"><FileText className="mx-auto mb-3"/>Create or select a report.</section>:<div className="space-y-5"><section className="border border-phantom-border bg-phantom-surface rounded-xl p-5 space-y-4"><div className="grid md:grid-cols-3 gap-3"><input value={active.title} onChange={e=>setActive({...active,title:e.target.value})} className="h-10 bg-phantom-bg border border-phantom-border rounded px-3 text-xs"/><select value={active.template} onChange={e=>setActive({...active,template:e.target.value})} className="h-10 bg-phantom-bg border border-phantom-border rounded px-3 text-xs"><option value="technical">Technical report</option><option value="executive">Executive report</option></select><select value={active.status} onChange={e=>setActive({...active,status:e.target.value})} className="h-10 bg-phantom-bg border border-phantom-border rounded px-3 text-xs">{['draft','review','final','archived'].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="grid md:grid-cols-2 gap-3"><input placeholder="Company / brand" value={active.branding?.company??''} onChange={e=>setActive({...active,branding:{...active.branding,company:e.target.value}})} className="h-10 bg-phantom-bg border border-phantom-border rounded px-3 text-xs"/><input placeholder="Client metadata" value={active.metadata?.client??''} onChange={e=>setActive({...active,metadata:{...active.metadata,client:e.target.value}})} className="h-10 bg-phantom-bg border border-phantom-border rounded px-3 text-xs"/></div>
 <label className="text-xs flex gap-2 items-center"><input type="checkbox" checked={active.include_evidence} onChange={e=>setActive({...active,include_evidence:e.target.checked})}/>Include finding evidence</label><div className="flex flex-wrap gap-2"><button onClick={()=>void save()} className="h-9 px-4 bg-phantom-cyan text-black rounded text-xs flex items-center gap-2"><Save size={13}/>Save new version</button><button onClick={()=>void download('pdf')} className="h-9 px-3 border border-phantom-border rounded text-xs flex gap-2 items-center"><Download size={13}/>PDF</button><button onClick={()=>void download('html')} className="h-9 px-3 border border-phantom-border rounded text-xs flex gap-2 items-center"><Download size={13}/>HTML</button></div></section>
 <section className="border border-phantom-border bg-phantom-surface rounded-xl p-5"><div className="flex items-center gap-2 mb-3"><ShieldAlert size={15}/><h2 className="text-sm font-semibold">Finding selection</h2></div><div className="space-y-2">{findings.map((f:any)=><label key={f.id} className="flex gap-3 p-3 border border-phantom-border rounded"><input type="checkbox" checked={selected.has(f.id)} onChange={()=>toggle(f.id)}/><div><div className="text-xs font-medium">{f.title}</div><div className="text-[10px] text-phantom-text-tertiary">{f.severity} · {f.status}</div></div></label>)}</div></section>
 <section className="bg-white text-black rounded shadow-2xl p-10"><div className="border-b pb-5 mb-6"><div className="text-xs uppercase">{active.branding?.company||'PHANTOM'}</div><h2 className="text-3xl font-bold">{active.title}</h2><p className="text-sm text-black/50">{scan?.target} · {active.template} · v{active.current_version} · {active.status}</p></div><div className="grid grid-cols-5 gap-2 mb-7">{Object.entries(counts).map(([s,n])=><div className="border rounded p-2 text-center" key={s}><b>{String(n)}</b><div className="text-[9px] uppercase">{s}</div></div>)}</div>{findings.filter((f:any)=>selected.has(f.id)).map((f:any)=><article key={f.id} className="border-t py-4"><h3 className="font-semibold">{f.title}</h3><p className="text-sm text-black/60 mt-2">{f.description}</p>{active.include_evidence&&<pre className="text-[10px] bg-black/5 p-2 mt-2 whitespace-pre-wrap">{JSON.stringify(f.evidence??{},null,2)}</pre>}</article>)}</section>
 <div className="grid md:grid-cols-2 gap-4"><section className="border border-phantom-border rounded-xl p-4"><div className="flex gap-2 text-xs font-semibold mb-2"><History size={13}/>Versions</div>{versions.slice(0,8).map(v=><div className="text-[11px] py-1" key={v.version}>v{v.version} · {new Date(v.created_at).toLocaleString()}</div>)}</section><section className="border border-phantom-border rounded-xl p-4"><div className="text-xs font-semibold mb-2">Download history</div>{downloads.slice(0,8).map((d,i)=><div className="text-[11px] py-1" key={i}>{d.format.toUpperCase()} · v{d.version} · {new Date(d.downloaded_at).toLocaleString()}</div>)}</section></div></div>}</div></div></main></div>
}