import React from 'react';
import { FileText, Download, Share2, Printer, LayoutTemplate } from 'lucide-react';

export default function Reports() {
  return (
    <div className="flex flex-col h-full bg-phantom-bg">
      <div className="flex-none p-6 border-b border-phantom-border bg-phantom-surface/50 backdrop-blur-xl z-10 sticky top-0">
        <div className="flex items-center justify-between mb-4">
          <h1 className="text-xl font-semibold tracking-tight">Report Builder</h1>
          <div className="flex gap-2">
            <button className="flex items-center gap-2 px-3 py-1.5 bg-phantom-panel border border-phantom-border rounded-md text-sm hover:text-phantom-text-primary transition-colors focus:outline-none">
              <LayoutTemplate size={14} /> Templates
            </button>
            <button className="flex items-center gap-2 px-4 py-1.5 bg-phantom-text-primary text-black rounded-md text-sm font-medium hover:opacity-90 transition-opacity focus:outline-none">
              <Download size={14} className="fill-black" /> Export PDF
            </button>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-auto p-8 flex justify-center bg-phantom-bg">
         {/* A4 Paper Mockup */}
         <div className="w-full max-w-[850px] min-h-[1100px] bg-white text-black p-12 rounded-sm shadow-2xl origin-top sm:scale-100 scale-90">
            <div className="flex justify-between items-end border-b-2 border-black/10 pb-6 mb-8">
               <div>
                 <h1 className="text-3xl font-bold tracking-tight text-black/90">Executive Security Summary</h1>
                 <p className="text-black/60 mt-2 font-medium">Generated by PHANTOM for ACME Corp</p>
               </div>
               <div className="text-right">
                 <div className="text-sm font-bold text-black/80">CONFIDENTIAL</div>
                 <div className="text-sm text-black/60">{new Date().toLocaleDateString()}</div>
               </div>
            </div>

            <div className="space-y-8">
              <section>
                <h2 className="text-xl font-bold text-black/80 mb-3 border-l-4 border-[#34d399] pl-3">1. Assessment Overview</h2>
                <p className="text-black/70 leading-relaxed text-base outline-none focus:bg-black/5 p-2 rounded transition-colors" contentEditable suppressContentEditableWarning>
                  Between October 10 and October 15, 2023, the Phantom security team performed a comprehensive authorized security assessment of the ACME Corp internal infrastructure and gateway services. The objective was to identify exploitable vulnerabilities that could impact confidentiality, integrity, or availability.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-bold text-black/80 mb-3 border-l-4 border-[#34d399] pl-3">2. Risk Posture</h2>
                <div className="grid grid-cols-4 gap-4 mb-6">
                  <div className="bg-red-50 border border-red-100 p-4 rounded-lg text-center">
                    <div className="text-3xl font-bold text-red-600">2</div>
                    <div className="text-sm font-medium text-red-800 mt-1 uppercase">Critical</div>
                  </div>
                  <div className="bg-orange-50 border border-orange-100 p-4 rounded-lg text-center">
                    <div className="text-3xl font-bold text-orange-600">14</div>
                    <div className="text-sm font-medium text-orange-800 mt-1 uppercase">High</div>
                  </div>
                  <div className="bg-teal-50 border border-teal-100 p-4 rounded-lg text-center">
                    <div className="text-3xl font-bold text-teal-600">45</div>
                    <div className="text-sm font-medium text-teal-800 mt-1 uppercase">Medium</div>
                  </div>
                  <div className="bg-gray-50 border border-gray-200 p-4 rounded-lg text-center">
                    <div className="text-3xl font-bold text-gray-600">112</div>
                    <div className="text-sm font-medium text-gray-700 mt-1 uppercase">Low</div>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-xl font-bold text-black/80 mb-3 border-l-4 border-[#34d399] pl-3">3. Key Findings & Remediation</h2>
                <div className="space-y-4">
                  <div className="border border-black/10 rounded-lg p-4">
                    <div className="flex justify-between items-start mb-2">
                       <h3 className="font-bold text-lg">curl heap-based buffer overflow (CVE-2023-38545)</h3>
                       <span className="px-2 py-1 bg-red-100 text-red-800 text-xs font-bold rounded uppercase">Critical</span>
                    </div>
                    <p className="text-black/70 mb-3 text-sm">Identified on <code>api.internal.corp</code>. This vulnerability allows potential remote code execution via malformed SOCKS5 requests.</p>
                    <div className="bg-gray-50 p-3 rounded border border-gray-200">
                      <h4 className="font-bold text-sm mb-1">Recommended Action</h4>
                      <p className="text-sm text-black/70">Update the curl library to version 8.4.0 or higher immediately on all affected nodes.</p>
                    </div>
                  </div>
                </div>
              </section>
            </div>
         </div>
      </div>
    </div>
  );
}
