import React,{useEffect,useState}from'react';
import{Bell,Key,Link2,Settings as SettingsIcon,Shield,Users,Webhook,ArrowRight,Mail}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{cn}from'../lib/utils';
import{authHeaders,getSession}from'../lib/auth';
const API=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');
const PROVIDERS=[
 {id:'slack',title:'Slack',icon:Webhook,help:'Incoming webhook URL',fields:['secret']},
 {id:'jira',title:'Jira Software',icon:Link2,help:'Atlassian API token',fields:['base_url','email','project_key','secret']},
 {id:'github',title:'GitHub',icon:Key,help:'Fine-grained token with Issues access',fields:['repo','secret']},
 {id:'pagerduty',title:'PagerDuty',icon:Bell,help:'Events API v2 routing key',fields:['secret']},
 {id:'email',title:'Email',icon:Mail,help:'SMTP password is stored as the secret',fields:['smtp_host','smtp_port','username','from_email','to_email','secret']},
];
type Integration={id:string;provider:string;name:string;enabled:boolean;status:string;config:Record<string,any>;has_secret:boolean;last_verified_at?:string;last_error?:string};
export default function Settings(){const[tab,setTab]=useState('general');const nav=useNavigate();const session=getSession();const[items,setItems]=useState<Integration[]>([]);const[edit,setEdit]=useState<string|null>(null);const[form,setForm]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[err,setErr]=useState('');
 const load=async()=>{const r=await fetch(API+'/api/v1/integrations',{headers:authHeaders()});if(r.ok)setItems(await r.json())};
 useEffect(()=>{if(tab==='integrations')load()},[tab]);
 const open=(p:any)=>{const i=items.find(x=>x.provider===p.id);setEdit(p.id);setErr('');setForm({...Object.fromEntries(Object.entries(i?.config||{}).map(([k,v])=>[k,String(v)])),secret:''})};
 const save=async(p:any)=>{setBusy(true);setErr('');const config={...form};delete config.secret;const r=await fetch(API+'/api/v1/integrations/'+p.id,{method:'PUT',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({provider:p.id,name:p.title,enabled:true,config,secret:form.secret||undefined})});if(!r.ok){setErr(await r.text());setBusy(false);return}const v=await fetch(API+'/api/v1/integrations/'+p.id+'/verify',{method:'POST',headers:authHeaders()});if(!v.ok)setErr(await v.text());else{setEdit(null);await load()}setBusy(false)};
 const disconnect=async(id:string)=>{setBusy(true);await fetch(API+'/api/v1/integrations/'+id,{method:'DELETE',headers:authHeaders()});await load();setBusy(false)};
 return <div className="flex flex-col h-full bg-phantom-bg"><header className="flex-none p-6 border-b border-phantom-border bg-phantom-surface/50"><h1 className="text-xl font-semibold tracking-tight mb-6">Settings</h1><div className="flex flex-wrap items-center gap-5">{['general','team','integrations','api'].map(x=><button key={x} onClick={()=>setTab(x)} className={cn('text-sm font-medium pb-3 border-b-2 capitalize',tab===x?'border-phantom-cyan text-phantom-text-primary':'border-transparent text-phantom-text-tertiary')}>{x==='api'?'API & Security':x==='team'?'Team & Roles':x}</button>)}</div></header><main className="flex-1 overflow-auto p-8"><div className="max-w-4xl space-y-5">
 {tab==='general'&&<section className="rounded-xl border border-phantom-border bg-phantom-surface p-5"><div className="text-xs font-mono uppercase tracking-wider text-phantom-cyan mb-2">Workspace</div><h2 className="text-lg font-medium">PHANTOM Security Workspace</h2><p className="text-sm text-phantom-text-secondary mt-2">Current operator: {session?.actor??'—'} · role: {session?.role??'—'}</p></section>}
 {tab==='team'&&<section className="rounded-xl border border-phantom-border bg-phantom-surface p-5"><div className="flex items-center gap-3"><Users size={18}/><div className="flex-1"><h2 className="font-medium">Team & roles</h2><p className="text-sm text-phantom-text-secondary">Workspace membership and permissions.</p></div><button onClick={()=>nav('/team')} className="h-9 px-3 rounded-lg border border-phantom-border text-xs flex gap-2 items-center">Open team <ArrowRight size={13}/></button></div></section>}
 {tab==='integrations'&&<><div><h2 className="text-lg font-medium">Integrations</h2><p className="text-sm text-phantom-text-secondary mt-1">A service is marked Connected only after PHANTOM successfully verifies its credentials.</p></div>{err&&<div className="p-3 border border-red-500/30 rounded-lg text-sm text-red-400">{err}</div>}<div className="space-y-3">{PROVIDERS.map(p=>{const i=items.find(x=>x.provider===p.id);const Icon=p.icon;const connected=i?.status==='connected';return <div key={p.id} className="p-5 border border-phantom-border rounded-xl bg-phantom-surface"><div className="flex gap-4"><div className="w-11 h-11 rounded-lg bg-phantom-panel flex items-center justify-center border border-phantom-border"><Icon size={20}/></div><div className="flex-1"><div className="flex justify-between gap-3"><h3 className="font-medium">{p.title}</h3><span className={cn('px-2 py-1 rounded border text-[10px] uppercase tracking-wider',connected?'border-emerald-500/30 text-emerald-400':'border-phantom-border text-phantom-text-tertiary')}>{connected?'Connected':i?.status==='error'?'Error':'Not connected'}</span></div><p className="text-sm text-phantom-text-secondary mt-1">{connected?'Verified '+(i?.last_verified_at?new Date(i.last_verified_at).toLocaleString():''):i?.last_error||p.help}</p><div className="mt-3 flex gap-2"><button onClick={()=>open(p)} className="h-8 px-3 rounded border border-phantom-border text-xs">{i?'Reconfigure':'Connect'}</button>{i&&<button disabled={busy} onClick={()=>disconnect(p.id)} className="h-8 px-3 rounded border border-phantom-border text-xs">Disconnect</button>}</div></div></div>{edit===p.id&&<div className="mt-4 border-t border-phantom-border pt-4 grid sm:grid-cols-2 gap-3">{p.fields.map(k=><label key={k} className="text-xs text-phantom-text-secondary">{k.replaceAll('_',' ')}<input type={k==='secret'?'password':'text'} placeholder={k==='secret'&&i?.has_secret?'Leave blank to keep current secret':''} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full bg-phantom-bg border border-phantom-border rounded-lg px-3 h-9 text-sm"/></label>)}<div className="sm:col-span-2 flex gap-2"><button disabled={busy} onClick={()=>save(p)} className="h-9 px-4 rounded-lg bg-phantom-cyan text-black text-xs font-medium">{busy?'Verifying…':'Save & verify'}</button><button onClick={()=>setEdit(null)} className="h-9 px-4 rounded-lg border border-phantom-border text-xs">Cancel</button></div></div>}</div>})}</div></>}
 {tab==='api'&&<section className="rounded-xl border border-phantom-border bg-phantom-surface p-5"><div className="flex items-center gap-3"><Shield size={18} className="text-phantom-cyan"/><div><h2 className="font-medium">API & security</h2><p className="text-sm text-phantom-text-secondary">Sessions, RBAC and scanner controls are enforced by the backend.</p></div></div></section>}
 </div></main></div>}
