import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,Copy,Pause,Play,RefreshCw,Wifi,WifiOff,X}from'lucide-react';
import{authHeaders}from'../lib/auth';
const API=(import.meta.env.VITE_PHANTOM_API_URL??'http://localhost:8000').replace(/\/$/,'');
type Worker={id:string;status:string;heartbeat:string|null;age_seconds:number|null;version:string;capacity:number|null;started_at:string|null;last_job:string|null;last_job_at:string|null};
type Status={api:{status:string;version:string};dependencies:{redis:{status:string;latency_ms:number|null};postgresql:{status:string;latency_ms:number|null};scheduler:{status:string;age_seconds:number|null}};redis:{stream:string;queue_length:number;pending:number};workers:Worker[];scans:{active:number;queued:number;failed:number;retries:number;stuck:number};metrics:any;failed_jobs:any[];stuck_jobs:any[]};
type Event={id:string;event_type:string;severity:string;message:string;scan_id:string|null;correlation_id:string|null;metadata:any;created_at:string|null};
export default function Terminal(){const[data,setData]=useState<Status|null>(null),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(''),[paused,setPaused]=useState(false),[severity,setSeverity]=useState(''),[scan,setScan]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<Event|null>(null),[worker,setWorker]=useState<Worker|null>(null);
const load=useCallback(async()=>{try{const h=authHeaders(),p=new URLSearchParams({limit:'200'});if(severity)p.set('severity',severity);if(scan)p.set('scan_id',scan);if(query)p.set('q',query);const[s,e]=await Promise.all([fetch(`${API}/api/v1/system/status`,{headers:h}),fetch(`${API}/api/v1/operations/events?${p}`,{headers:h})]);if(!s.ok||!e.ok)throw new Error('Operations telemetry unavailable');setData(await s.json());if(!paused)setEvents(await e.json());setError('')}catch(e){setError(e instanceof Error?e.message:'System status unavailable')}},[severity,scan,query,paused]);
useEffect(()=>{void load();const t=window.setInterval(()=>void load(),5000);return()=>clearInterval(t)},[load]);
const copy=(e:Event)=>navigator.clipboard?.writeText(JSON.stringify(e,null,2));
return <div className="min-h-full bg-phantom-bg p-6 lg:p-8"><div className="max-w-7xl mx-auto space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-mono uppercase tracking-widest text-phantom-cyan mb-2">Read-only operations console</div><h1 className="text-2xl font-semibold">System Terminal</h1><p className="text-sm text-phantom-text-secondary mt-1">Workers, queues, jobs, scheduler and dependency health without shell access.</p></div><div className="flex gap-2"><button onClick={()=>setPaused(x=>!x)} className="h-9 px-3 border border-phantom-border rounded text-xs flex gap-2 items-center">{paused?<Play size={13}/>:<Pause size={13}/>} {paused?'Resume':'Pause'}</button><button onClick={()=>void load()} className="h-9 px-3 border border-phantom-border rounded"><RefreshCw size={13}/></button></div></header>
{error&&<div className="border border-phantom-coral/30 bg-phantom-coral/10 p-3 rounded text-xs text-phantom-coral">{error}</div>}
<div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Metric label="Active" value={data?.scans.active??0}/><Metric label="Queued" value={data?.scans.queued??0}/><Metric label="Failed" value={data?.scans.failed??0}/><Metric label="Retries" value={data?.scans.retries??0}/><Metric label="Stuck" value={data?.scans.stuck??0}/></div>
<section className="grid md:grid-cols-4 gap-3"><Health label="API" status={data?.api.status}/><Health label="Redis" status={data?.dependencies.redis.status} detail={data?.dependencies.redis.latency_ms+' ms'}/><Health label="PostgreSQL" status={data?.dependencies.postgresql.status} detail={data?.dependencies.postgresql.latency_ms+' ms'}/><Health label="Scheduler" status={data?.dependencies.scheduler.status} detail={data?.dependencies.scheduler.age_seconds==null?'no heartbeat':data.dependencies.scheduler.age_seconds+'s ago'}/></section>
<div className="grid lg:grid-cols-[1fr_360px] gap-5"><section className="border border-phantom-border bg-[#050505] rounded-xl overflow-hidden"><div className="p-3 border-b border-phantom-border bg-phantom-surface grid md:grid-cols-3 gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter events…" className="h-9 px-3 bg-phantom-bg border border-phantom-border rounded text-xs"/><select value={severity} onChange={e=>setSeverity(e.target.value)} className="h-9 bg-phantom-bg border border-phantom-border rounded px-2 text-xs"><option value="">All severities</option>{['debug','info','warning','error','critical'].map(x=><option key={x}>{x}</option>)}</select><input value={scan} onChange={e=>setScan(e.target.value)} placeholder="Scan ID" className="h-9 px-3 bg-phantom-bg border border-phantom-border rounded text-xs"/></div><div className="max-h-[560px] overflow-auto p-3 font-mono text-[11px]">{events.map(e=><button key={e.id} onClick={()=>setSelected(e)} className="w-full text-left py-2 border-b border-white/5 hover:bg-white/5"><span className="text-phantom-text-tertiary">[{e.created_at?new Date(e.created_at).toLocaleTimeString():'—'}]</span> <span className="text-phantom-cyan">{e.severity}</span> <span>{e.event_type}</span> <span className="text-phantom-text-secondary">{e.message}</span>{e.correlation_id&&<span className="text-phantom-text-tertiary"> · corr {e.correlation_id.slice(0,12)}</span>}</button>)}</div></section>
<aside className="border border-phantom-border bg-phantom-surface rounded-xl p-4"><div className="text-xs uppercase text-phantom-text-tertiary mb-3">Workers</div>{data?.workers.map(w=><button key={w.id} onClick={()=>setWorker(w)} className="w-full flex gap-3 items-center py-3 border-b border-phantom-border text-left">{w.status==='online'?<Wifi size={14} className="text-phantom-cyan"/>:<WifiOff size={14}/>}<div className="min-w-0"><div className="text-xs truncate">{w.id}</div><div className="text-[10px] text-phantom-text-tertiary">v{w.version} · capacity {w.capacity??'—'} · {w.status}</div></div></button>)}</aside></div>
<div className="grid md:grid-cols-2 gap-4"><Jobs title="Failed jobs" rows={data?.failed_jobs??[]}/><Jobs title="Stuck jobs" rows={data?.stuck_jobs??[]}/></div>
{selected&&<Modal close={()=>setSelected(null)}><div className="flex justify-between"><h2 className="font-semibold">Event detail</h2><button onClick={()=>void copy(selected)}><Copy size={15}/></button></div><pre className="mt-4 text-xs whitespace-pre-wrap break-all">{JSON.stringify(selected,null,2)}</pre></Modal>}{worker&&<Modal close={()=>setWorker(null)}><h2 className="font-semibold">Worker detail</h2><pre className="mt-4 text-xs whitespace-pre-wrap break-all">{JSON.stringify(worker,null,2)}</pre></Modal>}</div></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="border border-phantom-border bg-phantom-surface rounded-xl p-4"><div className="text-[10px] uppercase text-phantom-text-tertiary">{label}</div><div className="text-2xl font-mono mt-2">{value}</div></div>}
function Health({label,status,detail}:{label:string;status?:string;detail?:string}){return <div className="border border-phantom-border bg-phantom-surface rounded-xl p-3"><div className="text-xs font-medium">{label}</div><div className="text-[11px] mt-1">{status??'unknown'} <span className="text-phantom-text-tertiary">{detail}</span></div></div>}
function Jobs({title,rows}:{title:string;rows:any[]}){return <section className="border border-phantom-border rounded-xl p-4"><h3 className="text-xs font-semibold mb-2">{title}</h3>{rows.length?rows.map(x=><div key={x.id} className="py-2 border-b border-phantom-border text-xs"><div className="font-mono">{x.id}</div><div className="text-phantom-text-tertiary truncate">{x.target} {x.error&&'· '+x.error}</div></div>):<div className="text-xs text-phantom-text-tertiary">None detected.</div>}</section>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="fixed inset-0 bg-black/70 z-50 flex justify-end" onClick={close}><div className="w-full max-w-xl h-full bg-phantom-surface border-l border-phantom-border p-6 overflow-auto" onClick={e=>e.stopPropagation()}><button onClick={close} className="float-right"><X size={17}/></button>{children}</div></div>}
