import React, { useEffect, useMemo, useState } from 'react';
import { Search, Filter, X, UserRound, FileJson, Clock3, ExternalLink } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '../lib/utils';

const API = (import.meta.env.VITE_PHANTOM_API_URL ?? 'http://localhost:8000').replace(/\/$/, '');
const SEVERITIES = ['all', 'critical', 'high', 'medium', 'low', 'info'];
const STATUSES = ['all', 'open', 'triaged', 'assigned', 'in_remediation', 'fixed', 'verified', 'closed', 'accepted_risk', 'false_positive'];
type Finding = { id:string; scan_id:string; module:string; title:string; severity:string; status:string; fingerprint:string; cve?:string|null; cwe?:string|null; cvss?:number|null; assignee?:string|null; description:string; remediation:string; evidence:Record<string,unknown>; confidence:number; first_seen?:string; last_seen?:string };

function Badge({ severity }:{severity:string}) { const tone=severity==='critical'?'text-phantom-coral border-phantom-coral/30 bg-phantom-coral/5':severity==='high'?'text-phantom-amber border-phantom-amber/30 bg-phantom-amber/5':'text-phantom-text-secondary border-phantom-border bg-phantom-bg'; return <span className={cn('inline-flex px-2 py-1 rounded text-[10px] font-semibold tracking-wider border',tone)}>{severity.toUpperCase()}</span>; }
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}) { return <label className="flex items-center gap-2 h-9 px-2.5 border border-phantom-border bg-phantom-panel rounded-lg text-xs"><span className="text-phantom-text-tertiary">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="bg-transparent outline-none capitalize">{options.map(x=><option key={x}>{x.replace('_',' ')}</option>)}</select></label>; }

export default function Vulnerabilities() {
 const [findings,setFindings]=useState<Finding[]>([]),[selected,setSelected]=useState<Finding|null>(null),[search,setSearch]=useState(''),[severity,setSeverity]=useState('all'),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch(`${API}/api/v1/findings`);if(!r.ok)throw new Error();setFindings(await r.json())}catch{setFindings([])}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>findings.filter(f=>(severity==='all'||f.severity.toLowerCase()===severity)&&(status==='all'||f.status===status)&&`${f.title} ${f.module} ${f.cve??''} ${f.cwe??''} ${f.assignee??''}`.toLowerCase().includes(search.toLowerCase())),[findings,search,severity,status]);
 return <div className="flex h-full bg-phantom-bg relative overflow-hidden"><div className={cn('flex flex-col h-full flex-1 min-w-0',selected&&'lg:pr-[440px]')}>
  <header className="p-6 border-b border-phantom-border bg-phantom-surface"><div className="flex items-start justify-between mb-5"><div><div className="text-[10px] font-mono uppercase tracking-widest text-phantom-cyan mb-2">Finding operations</div><h1 className="text-xl font-semibold">Vulnerabilities</h1><p className="text-sm text-phantom-text-secondary mt-1">Findings persisted by PHANTOM assessments.</p></div><button onClick={load} className="px-3 py-2 text-xs border border-phantom-border rounded-lg hover:bg-phantom-panel">Refresh</button></div>
   <div className="flex flex-wrap gap-2"><div className="relative flex-1 min-w-[220px] max-w-md"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-phantom-text-tertiary"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search finding, CVE, module, assignee..." className="w-full h-9 pl-9 pr-3 bg-phantom-panel border border-phantom-border rounded-lg text-xs outline-none focus:border-phantom-cyan"/></div><Select label="Severity" value={severity} options={SEVERITIES} onChange={setSeverity}/><Select label="Status" value={status} options={STATUSES} onChange={setStatus}/></div>
  </header><main className="flex-1 overflow-auto p-6"><div className="border border-phantom-border rounded-xl bg-phantom-surface overflow-hidden"><div className="grid grid-cols-[minmax(260px,2fr)_120px_130px_130px_90px] px-4 py-3 border-b border-phantom-border bg-phantom-panel/50 text-[10px] font-semibold uppercase tracking-wider text-phantom-text-tertiary"><span>Finding</span><span>Severity</span><span>Status</span><span>Assignee</span><span>Confidence</span></div>
   {loading?<div className="p-12 text-center text-sm text-phantom-text-tertiary">Loading findings…</div>:filtered.length===0?<div className="p-12 text-center"><Filter size={18} className="mx-auto mb-3 text-phantom-text-tertiary"/><div className="text-sm">No findings match the current filters.</div><div className="text-xs text-phantom-text-tertiary mt-1">Run an authorized assessment or adjust the filters.</div></div>:filtered.map(f=><button key={f.id} onClick={()=>setSelected(f)} className="w-full grid grid-cols-[minmax(260px,2fr)_120px_130px_130px_90px] items-center px-4 py-3 border-b last:border-0 border-phantom-border text-left hover:bg-phantom-panel-hover"><div className="min-w-0 pr-4"><div className="text-sm font-medium truncate">{f.title}</div><div className="text-[10px] font-mono text-phantom-text-tertiary mt-1 truncate">{f.module} · {f.cve??'No CVE'} · {f.id.slice(0,8)}</div></div><div><Badge severity={f.severity}/></div><div><span className="text-[11px] px-2 py-1 rounded border border-phantom-border bg-phantom-bg capitalize">{f.status.replaceAll('_',' ')}</span></div><div className="text-xs text-phantom-text-secondary truncate">{f.assignee??'Unassigned'}</div><div className="text-xs font-mono">{Math.round(f.confidence*100)}%</div></button>)}
  </div></main></div><AnimatePresence>{selected&&<motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} className="absolute right-0 top-0 bottom-0 w-full max-w-[440px] bg-phantom-panel border-l border-phantom-border shadow-2xl z-20 flex flex-col"><FindingPanel finding={selected} onClose={()=>setSelected(null)} onUpdated={f=>{setSelected(f);setFindings(x=>x.map(v=>v.id===f.id?f:v))}}/></motion.aside>}</AnimatePresence></div>;
}

function FindingPanel({finding,onClose,onUpdated}:{finding:Finding;onClose:()=>void;onUpdated:(f:Finding)=>void}) { const [saving,setSaving]=useState(false),[assignee,setAssignee]=useState(finding.assignee??''); const next=['open','triaged','assigned','in_remediation','fixed','verified','closed','accepted_risk','false_positive'].filter(x=>x!==finding.status); async function patch(body:Record<string,unknown>){setSaving(true);try{const r=await fetch(`${API}/api/v1/findings/${finding.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail??'Update failed');onUpdated(d)}catch(e){alert(e instanceof Error?e.message:'Update failed')}finally{setSaving(false)}} return <><div className="p-4 border-b border-phantom-border bg-phantom-surface flex items-start justify-between"><div><div className="flex items-center gap-2 mb-2"><Badge severity={finding.severity}/><span className="font-mono text-[10px] text-phantom-text-tertiary">{finding.id.slice(0,8)}</span></div><h2 className="font-semibold text-sm">{finding.title}</h2></div><button onClick={onClose} className="p-2 hover:bg-phantom-bg rounded"><X size={17}/></button></div>
 <div className="flex-1 overflow-auto p-4 space-y-6"><div className="grid grid-cols-2 gap-2">{[['Status',finding.status.replaceAll('_',' ')],['CVSS',finding.cvss??'—'],['CVE',finding.cve??'—'],['CWE',finding.cwe??'—']].map(([l,v])=><div key={l} className="p-3 rounded-lg border border-phantom-border bg-phantom-surface"><div className="text-[9px] uppercase tracking-wider text-phantom-text-tertiary mb-1">{l}</div><div className="text-xs capitalize">{v}</div></div>)}</div>
 <section><div className="text-xs font-semibold mb-2">Workflow</div><select disabled={saving} defaultValue="" onChange={e=>e.target.value&&patch({status:e.target.value})} className="w-full h-9 px-2 rounded border border-phantom-border bg-phantom-surface text-xs"><option value="">Move finding…</option>{next.map(s=><option key={s}>{s.replaceAll('_',' ')}</option>)}</select></section>
 <section><div className="text-xs font-semibold mb-2 flex items-center gap-2"><UserRound size={13}/> Assignee</div><div className="flex gap-2"><input value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder="analyst@team" className="flex-1 h-9 px-2.5 rounded border border-phantom-border bg-phantom-surface text-xs outline-none focus:border-phantom-cyan"/><button disabled={saving} onClick={()=>patch({assignee})} className="px-3 h-9 rounded border border-phantom-border text-xs">Save</button></div></section>
 <section><div className="text-xs font-semibold mb-2">Description</div><p className="text-xs text-phantom-text-secondary leading-relaxed">{finding.description||'No description recorded.'}</p></section><section><div className="text-xs font-semibold mb-2">Remediation</div><div className="p-3 rounded-lg border border-phantom-border bg-phantom-surface text-xs text-phantom-text-secondary leading-relaxed">{finding.remediation||'No remediation guidance recorded.'}</div></section><section><div className="text-xs font-semibold mb-2 flex items-center gap-2"><FileJson size={13}/> Evidence</div><pre className="max-h-64 overflow-auto p-3 rounded-lg border border-phantom-border bg-phantom-bg text-[10px] font-mono text-phantom-text-secondary whitespace-pre-wrap">{JSON.stringify(finding.evidence??{},null,2)}</pre></section><section className="grid grid-cols-2 gap-2"><div className="text-[10px] text-phantom-text-tertiary"><Clock3 size={11} className="inline mr-1"/>First seen<br/><span className="text-xs text-phantom-text-secondary">{finding.first_seen?new Date(finding.first_seen).toLocaleString():'—'}</span></div><div className="text-[10px] text-phantom-text-tertiary"><Clock3 size={11} className="inline mr-1"/>Last seen<br/><span className="text-xs text-phantom-text-secondary">{finding.last_seen?new Date(finding.last_seen).toLocaleString():'—'}</span></div></section><a href={`${API}/api/v1/scans/${finding.scan_id}`} target="_blank" rel="noreferrer" className="text-xs text-phantom-cyan inline-flex items-center gap-1">Open source scan <ExternalLink size={12}/></a></div></>; }
