import React,{createContext,useContext,useEffect,useState}from'react';
import{AlertTriangle,CheckCircle2,ChevronLeft,ChevronRight,Inbox,Loader2,Search as SearchIcon,X}from'lucide-react';
import{cn}from'../../lib/utils';

export const buttonVariants={primary:'bg-phantom-cyan text-black hover:opacity-90',secondary:'border border-phantom-border bg-phantom-surface hover:bg-phantom-panel',danger:'border border-phantom-coral/30 text-phantom-coral hover:bg-phantom-coral/5',ghost:'hover:bg-phantom-panel text-phantom-text-secondary'};
export function Button({variant='secondary',className='',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:keyof typeof buttonVariants}){return <button {...p} className={cn('h-9 px-3 rounded-lg text-xs font-medium inline-flex items-center justify-center gap-2 transition disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:ring-2 focus:ring-phantom-cyan/40',buttonVariants[variant],className)}/>}
export function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className={cn('h-9 w-full px-3 rounded-lg border border-phantom-border bg-phantom-panel text-xs outline-none focus:border-phantom-cyan disabled:opacity-50',p.className)}/>}
export function Select({options,...p}:React.SelectHTMLAttributes<HTMLSelectElement>&{options?:{value:string;label:string}[]}){return <select {...p} className={cn('h-9 px-3 rounded-lg border border-phantom-border bg-phantom-panel text-xs outline-none focus:border-phantom-cyan',p.className)}>{options?.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}{p.children}</select>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'info'}){const t={neutral:'border-phantom-border text-phantom-text-secondary',success:'border-emerald-500/30 text-emerald-400',warning:'border-phantom-amber/30 text-phantom-amber',danger:'border-phantom-coral/30 text-phantom-coral',info:'border-phantom-cyan/30 text-phantom-cyan'}[tone];return <span className={cn('inline-flex px-2 py-1 rounded border bg-phantom-bg text-[10px] font-semibold uppercase tracking-wider',t)}>{children}</span>}
export function Severity({value}:{value:string}){const v=value.toLowerCase();return <Badge tone={v==='critical'||v==='high'?'danger':v==='medium'?'warning':v==='low'?'info':'neutral'}>{value}</Badge>}
export function Search({value,onChange,placeholder='Search…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative"><SearchIcon size={14} className="absolute left-3 top-2.5 text-phantom-text-tertiary"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="pl-9"/></div>}
export function EmptyState({title='Nothing here',description,action}:{title?:string;description?:string;action?:React.ReactNode}){return <div className="p-12 text-center"><Inbox size={20} className="mx-auto mb-3 text-phantom-text-tertiary"/><div className="text-sm font-medium">{title}</div>{description&&<div className="text-xs text-phantom-text-tertiary mt-1">{description}</div>}{action&&<div className="mt-4">{action}</div>}</div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="p-4 rounded-lg border border-phantom-coral/20 bg-phantom-coral/5 text-xs text-phantom-coral flex items-center gap-2"><AlertTriangle size={14}/><span className="flex-1">{message}</span>{retry&&<Button variant="danger" onClick={retry}>Retry</Button>}</div>}
export function LoadingState({label='Loading…'}:{label?:string}){return <div className="p-12 flex items-center justify-center gap-2 text-sm text-phantom-text-tertiary"><Loader2 size={16} className="animate-spin"/>{label}</div>}
export function Modal({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:React.ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" onMouseDown={onClose}><div onMouseDown={e=>e.stopPropagation()} className="w-full max-w-lg rounded-xl border border-phantom-border bg-phantom-surface shadow-2xl"><div className="p-4 border-b border-phantom-border flex items-center justify-between"><h2 className="font-medium">{title}</h2><Button variant="ghost" className="w-9 px-0" onClick={onClose}><X size={16}/></Button></div><div className="p-4">{children}</div></div></div>}
export function Drawer({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:React.ReactNode}){return <div className={cn('fixed z-40 top-0 right-0 h-full w-full max-w-[440px] border-l border-phantom-border bg-phantom-panel shadow-2xl transition-transform',open?'translate-x-0':'translate-x-full')}><div className="p-4 border-b border-phantom-border flex justify-between"><h2>{title}</h2><Button variant="ghost" className="w-9 px-0" onClick={onClose}><X size={16}/></Button></div><div className="h-[calc(100%-65px)] overflow-auto">{children}</div></div>}
export function Table({children}:{children:React.ReactNode}){return <div className="overflow-auto rounded-xl border border-phantom-border bg-phantom-surface"><table className="w-full text-left text-xs">{children}</table></div>}
export function Pagination({page,pages,onChange}:{page:number;pages:number;onChange:(n:number)=>void}){return <div className="flex items-center justify-end gap-2 py-3"><Button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={13}/></Button><span className="text-xs text-phantom-text-tertiary">Page {page} of {Math.max(1,pages)}</span><Button disabled={page>=pages} onClick={()=>onChange(page+1)}><ChevronRight size={13}/></Button></div>}
export function FilterBar({children}:{children:React.ReactNode}){return <div className="flex flex-wrap items-center gap-2">{children}</div>}
export const formatDateTime=(value?:string|Date|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';

type Toast={id:number;message:string;tone:'success'|'error'};
const ToastContext=createContext<(m:string,t?:Toast['tone'])=>void>(()=>{});
export function ToastProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<Toast[]>([]);const push=(message:string,tone:Toast['tone']='success')=>{const id=Date.now();setItems(x=>[...x,{id,message,tone}]);setTimeout(()=>setItems(x=>x.filter(v=>v.id!==id)),3500)};return <ToastContext.Provider value={push}>{children}<div className="fixed right-4 bottom-4 z-[70] space-y-2">{items.map(t=><div key={t.id} className={cn('min-w-64 rounded-lg border bg-phantom-surface p-3 text-xs shadow-xl flex gap-2',t.tone==='error'?'border-phantom-coral/30':'border-emerald-500/30')}>{t.tone==='error'?<AlertTriangle size={14}/>:<CheckCircle2 size={14}/>} {t.message}</div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);
export function ConfirmDialog({open,title,description,confirmLabel='Confirm',danger=false,onConfirm,onClose}:{open:boolean;title:string;description:string;confirmLabel?:string;danger?:boolean;onConfirm:()=>void;onClose:()=>void}){return <Modal open={open} title={title} onClose={onClose}><p className="text-sm text-phantom-text-secondary">{description}</p><div className="mt-5 flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button variant={danger?'danger':'primary'} onClick={onConfirm}>{confirmLabel}</Button></div></Modal>}
